apiVersion: v1
kind: Service
metadata:
  name: students-service
  namespace: devops
spec:
  selector:
    app: students-management
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort